BASE                  <http://dbpedia.org/resource/>
PREFIX dbpedia-owl:   <http://dbpedia.org/ontology/>
PREFIX dbpprop:       <http://dbpedia.org/property/>

SELECT DISTINCT * WHERE
{
    ?uni dbpprop:type <Private_university>    .
    { ?uni dbpprop:location <Los_Angeles,_California> } UNION { ?uni dbpprop:city <Los_Angeles> } UNION { ?uni dbpedia-owl:city <Los_Angeles> }    .
    OPTIONAL { ?uni dbpedia-owl:numberOfStudents ?num  }  .
}
ORDER BY DESC(?num)
