BASE                  <http://dbpedia.org/resource/>
PREFIX dbpedia-owl:   <http://dbpedia.org/ontology/>
PREFIX dbpprop:       <http://dbpedia.org/property/>

SELECT distinct ?university, ?established_years WHERE
{
    { ?university dbpprop:type <Public_university> } UNION { ?university dbpprop:type <Private_university> }    .
    { ?university dbpprop:location <Los_Angeles> } UNION { ?university dbpprop:city <Los_Angeles> } UNION { ?university dbpedia-owl:city <Los_Angeles> }    .
    ?university dbpprop:established ?established_raw    .
    BIND(IF(DATATYPE(?established_raw) = xsd:date, YEAR(?established_raw), ?established_raw) AS ?established)    .
    BIND(YEAR(NOW()) - ?established AS ?established_years)    .
    FILTER(?established_years > 100)    .
}
ORDER BY ASC(?established_years)
