BASE                  <http://dbpedia.org/resource/>
PREFIX dbpedia-owl:   <http://dbpedia.org/ontology/>

SELECT * WHERE
{
    { <University_of_Southern_California> dbpedia-owl:numberOfStudents ?num } UNION { <University_of_California,_Los_Angeles> dbpedia-owl:numberOfStudents ?num }    .
}
